import { createFileRoute, Link } from "@tanstack/react-router";
import { StaffLayout } from "@/components/portal/StaffLayout";
import { ArrowRight, FileText, HeartPulse, Plus, ScanLine, ShieldCheck, Stethoscope, UserPlus, Users, UserRound } from "lucide-react";
import { getDoctors, getPatients, getStaff } from "@/data/clinovaStore";

export const Route = createFileRoute("/staff/")({ component: StaffDashboard });

function StaffDashboard() {
  const doctors = getDoctors();
  const staff = getStaff();
  const patients = getPatients();

  const cards = [
    { to: "/staff/doctors", icon: <Stethoscope />, title: "Doctors", text: "Create doctor profiles, generate Doctor IDs and manage access.", count: doctors.length },
    { to: "/staff/staff", icon: <Users />, title: "Staff", text: "Create staff accounts and assign operational roles.", count: staff.length },
    { to: "/staff/patients", icon: <UserRound />, title: "Patients", text: "Register patients, assign doctors and manage accounts.", count: patients.length },
    { to: "/staff/digitize", icon: <ScanLine />, title: "Digitization", text: "Upload previous medical reports with staff assistance.", count: patients.reduce((n, p) => n + p.documents.length, 0) },
  ];

  return (
    <StaffLayout>
      <div className="mb-8">
        <p className="text-sm font-medium text-primary">CLINOVA • HEALTH CENTRE</p>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight">Health Centre Administration</h1>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">
          Manage the centre's doctors, staff and patients from one workspace. Human-readable IDs are generated by the application and will later be issued by the backend.
        </p>
      </div>

      <div className="mt-8 grid gap-5 lg:grid-cols-2">
        <div className="rounded-2xl border border-border bg-card p-6 shadow-sm lg:p-8">
          <div className="flex items-start gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><UserPlus className="h-5 w-5" /></div>
            <div>
              <h2 className="font-semibold">Start patient registration</h2>
              <p className="mt-1 text-sm leading-6 text-muted-foreground">Create the patient account, choose a doctor and optionally digitize previous history immediately.</p>
              <Link to="/staff/patients/register" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Register Patient <Plus className="h-4 w-4" /></Link>
            </div>
          </div>
        </div>
        
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        {cards.map((card) => (
          <Link key={card.to} to={card.to as never} className="rounded-2xl border border-border bg-card p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary">{card.icon}</div>
            <div className="mt-5 flex items-end justify-between gap-3">
              <h2 className="font-semibold">{card.title}</h2>
              <span className="text-2xl font-semibold">{card.count}</span>
            </div>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">{card.text}</p>
            <span className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-primary">Open <ArrowRight className="h-4 w-4" /></span>
          </Link>
        ))}
      </div>

     

        <div className="rounded-2xl border border-border bg-card p-6 shadow-sm lg:p-8">
          <div className="flex items-start gap-4">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileText className="h-5 w-5" /></div>
            <div>
              <h2 className="font-semibold">Identity structure</h2>
              <p className="mt-1 text-sm leading-6 text-muted-foreground">Every health centre, doctor, staff member and patient has a centre-scoped human-readable ID. Internal database UUIDs will be added later.</p>
              <div className="mt-4 grid grid-cols-2 gap-3 text-xs">
                <Badge label="Centre" value="HC-GJ-00001" />
                <Badge label="Doctor" value="DOC-GJ-00001" />
                <Badge label="Staff" value="STF-GJ-00001" />
                <Badge label="Patient" value="PAT-GJ-00001" />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-6 flex items-center gap-3 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm">
        <ShieldCheck className="h-5 w-5 shrink-0 text-primary" />
        <span>Prototype only: authentication, permissions, consent and audit logging are not yet connected to a backend.</span>
      </div>
    </StaffLayout>
  );
}

function Badge({ label, value }: { label: string; value: string }) {
  return <div className="rounded-lg border border-border bg-background p-3"><p className="text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>;
}
